# Generated by Django 5.2.4 on 2025-07-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Personal description or artist statement for public profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Indicates if user's identity has been verified by platform"),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text="User's city/location for local chapter assignment and shipping", max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional phone number for account verification and communication', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text="User's profile picture displayed throughout the platform", null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Social media profiles stored as JSON (Instagram, Twitter, etc.)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last profile update timestamp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('artist', 'Artist'), ('buyer', 'Buyer'), ('admin', 'Admin')], default='buyer', help_text='Defines user role and available features', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Personal or professional website URL'),
        ),
    ]
