# Generated by Django 5.2.4 on 2025-07-03 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="commissionrequest",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commission_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commissionproposal",
            name="commission_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proposal",
                to="commissions.commissionrequest",
            ),
        ),
        migrations.AddField(
            model_name="commissionpayment",
            name="commission_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="commissions.commissionrequest",
            ),
        ),
        migrations.AddField(
            model_name="commissionmilestone",
            name="commission_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="commissions.commissionrequest",
            ),
        ),
        migrations.AddField(
            model_name="commissioncontract",
            name="commission_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract",
                to="commissions.commissionrequest",
            ),
        ),
        migrations.AddField(
            model_name="commissionreview",
            name="commission_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="commissions.commissionrequest",
            ),
        ),
    ]
