# Generated by Django 5.2.4 on 2025-07-04 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artistprofile_artist_statement_and_more'),
        ('commissions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissioncontract',
            name='artist_signed',
            field=models.BooleanField(default=False, help_text='Whether artist has digitally agreed to contract terms'),
        ),
        migrations.AlterField(
            model_name='commissioncontract',
            name='artist_signed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when artist signed the contract', null=True),
        ),
        migrations.AlterField(
            model_name='commissioncontract',
            name='client_signed',
            field=models.BooleanField(default=False, help_text='Whether client has digitally agreed to contract terms'),
        ),
        migrations.AlterField(
            model_name='commissioncontract',
            name='client_signed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when client signed the contract', null=True),
        ),
        migrations.AlterField(
            model_name='commissioncontract',
            name='commission_request',
            field=models.OneToOneField(help_text='The commission request this contract formalizes', on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='commissions.commissionrequest'),
        ),
        migrations.AlterField(
            model_name='commissioncontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When contract was first created'),
        ),
        migrations.AlterField(
            model_name='commissioncontract',
            name='expected_completion_date',
            field=models.DateField(help_text='Target completion date agreed by both parties'),
        ),
        migrations.AlterField(
            model_name='commissioncontract',
            name='final_price',
            field=models.DecimalField(decimal_places=2, help_text='Agreed final price for the commission', max_digits=10),
        ),
        migrations.AlterField(
            model_name='commissioncontract',
            name='start_date',
            field=models.DateField(help_text='When artist will begin work on the commission'),
        ),
        migrations.AlterField(
            model_name='commissioncontract',
            name='terms_agreed',
            field=models.TextField(help_text='Final terms and conditions both parties have agreed to'),
        ),
        migrations.AlterField(
            model_name='commissionmilestone',
            name='commission_request',
            field=models.ForeignKey(help_text='The commission this milestone belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='commissions.commissionrequest'),
        ),
        migrations.AlterField(
            model_name='commissionmilestone',
            name='description',
            field=models.TextField(help_text='Detailed description of what will be delivered at this stage'),
        ),
        migrations.AlterField(
            model_name='commissionmilestone',
            name='order',
            field=models.PositiveIntegerField(help_text='Sequence order of this milestone in the project (1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='commissionmilestone',
            name='payment_percentage',
            field=models.PositiveIntegerField(help_text='Percentage of total payment released upon milestone completion'),
        ),
        migrations.AlterField(
            model_name='commissionmilestone',
            name='percentage',
            field=models.PositiveIntegerField(help_text='Percentage of total work completed at this milestone'),
        ),
        migrations.AlterField(
            model_name='commissionmilestone',
            name='progress_images',
            field=models.JSONField(blank=True, default=list, help_text='URLs of work-in-progress images for this milestone'),
        ),
        migrations.AlterField(
            model_name='commissionmilestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested')], default='pending', help_text='Current status of this milestone', max_length=20),
        ),
        migrations.AlterField(
            model_name='commissionmilestone',
            name='title',
            field=models.CharField(help_text="Name of this milestone (e.g., 'Initial Sketch', 'Color Study')", max_length=200),
        ),
        migrations.AlterField(
            model_name='commissionproposal',
            name='commission_request',
            field=models.OneToOneField(help_text='The commission request this proposal responds to', on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='commissions.commissionrequest'),
        ),
        migrations.AlterField(
            model_name='commissionproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When artist submitted this proposal'),
        ),
        migrations.AlterField(
            model_name='commissionproposal',
            name='estimated_completion_time',
            field=models.PositiveIntegerField(help_text='Estimated days to complete the artwork from start'),
        ),
        migrations.AlterField(
            model_name='commissionproposal',
            name='milestone_plan',
            field=models.JSONField(blank=True, default=list, help_text='Breakdown of project stages with timelines and payment percentages'),
        ),
        migrations.AlterField(
            model_name='commissionproposal',
            name='proposal_description',
            field=models.TextField(help_text="Artist's interpretation of the request and approach to the work"),
        ),
        migrations.AlterField(
            model_name='commissionproposal',
            name='proposed_price',
            field=models.DecimalField(decimal_places=2, help_text="Artist's quoted price for completing the commission", max_digits=10),
        ),
        migrations.AlterField(
            model_name='commissionproposal',
            name='sample_images',
            field=models.JSONField(blank=True, default=list, help_text="URLs of artist's previous similar work to demonstrate capability"),
        ),
        migrations.AlterField(
            model_name='commissionproposal',
            name='terms_and_conditions',
            field=models.TextField(help_text="Artist's terms, payment schedule, and project conditions"),
        ),
        migrations.AlterField(
            model_name='commissionproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time proposal was modified'),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='additional_requirements',
            field=models.TextField(blank=True, help_text='Any special requirements, materials, or style preferences'),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='artist',
            field=models.ForeignKey(help_text='Artist being asked to create the custom work', on_delete=django.db.models.deletion.CASCADE, related_name='commission_requests', to='artists.artistprofile'),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='budget_max',
            field=models.DecimalField(decimal_places=2, help_text='Maximum amount client is willing to pay', max_digits=10),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='budget_min',
            field=models.DecimalField(decimal_places=2, help_text='Minimum amount client is willing to pay', max_digits=10),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='client',
            field=models.ForeignKey(help_text='Customer requesting the custom artwork', on_delete=django.db.models.deletion.CASCADE, related_name='commission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='commission_type',
            field=models.CharField(choices=[('painting', 'Painting'), ('sculpture', 'Sculpture'), ('mural', 'Mural'), ('portrait', 'Portrait'), ('digital_art', 'Digital Art'), ('illustration', 'Illustration'), ('other', 'Other')], help_text='Category of artwork being requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When commission request was submitted'),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='deadline',
            field=models.DateField(help_text='When client needs the artwork completed by'),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='description',
            field=models.TextField(help_text='Detailed description of what client wants created'),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Desired size/dimensions of finished artwork', max_length=100),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='reference_images',
            field=models.JSONField(blank=True, default=list, help_text='URLs of reference images to guide the artist'),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', help_text='Current stage of the commission request', max_length=20),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='title',
            field=models.CharField(help_text='Brief title describing the requested artwork', max_length=200),
        ),
        migrations.AlterField(
            model_name='commissionrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time request details or status were updated'),
        ),
        migrations.AlterModelTable(
            name='commissionproposal',
            table=None,
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='commissions.commissionrequest')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
