# Generated by Django 5.2.4 on 2025-07-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="artist_logos/"),
                ),
                ("portfolio_images", models.JSONField(blank=True, default=list)),
                ("specializations", models.JSONField(blank=True, default=list)),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("education", models.TextField(blank=True)),
                ("awards", models.TextField(blank=True)),
                ("artist_statement", models.TextField(blank=True)),
                ("commission_available", models.BooleanField(default=True)),
                (
                    "commission_price_range",
                    models.CharField(blank=True, max_length=100),
                ),
                ("response_time", models.CharField(default="24 hours", max_length=50)),
                ("featured", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Artist Profile",
                "verbose_name_plural": "Artist Profiles",
                "db_table": "artist_profiles",
            },
        ),
        migrations.CreateModel(
            name="ArtistReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Artist Review",
                "verbose_name_plural": "Artist Reviews",
                "db_table": "artist_reviews",
            },
        ),
    ]
