# Generated by Django 5.2.4 on 2025-07-04 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='artist_statement',
            field=models.TextField(blank=True, help_text='Personal artistic philosophy and approach description'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='awards',
            field=models.TextField(blank=True, help_text='Notable awards, exhibitions, and recognitions'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='commission_available',
            field=models.BooleanField(default=True, help_text='Whether artist is currently accepting commission requests'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='commission_price_range',
            field=models.CharField(blank=True, help_text="Typical price range for commissioned work (e.g., '$500-$2000')", max_length=100),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When artist profile was first created'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='display_name',
            field=models.CharField(help_text="Artist's professional name shown publicly", max_length=100),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='education',
            field=models.TextField(blank=True, help_text='Educational background and art-related qualifications'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Number of years artist has been practicing professionally'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='featured',
            field=models.BooleanField(default=False, help_text='Whether artist is featured prominently on platform'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text="Artist's brand logo or signature artwork", null=True, upload_to='artist_logos/'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='portfolio_images',
            field=models.JSONField(blank=True, default=list, help_text="Array of portfolio image URLs showcasing artist's work"),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average customer rating (0.00 to 5.00)', max_digits=3),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='response_time',
            field=models.CharField(default='24 hours', help_text='How quickly artist typically responds to inquiries', max_length=50),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of artist name for profile URLs', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='specializations',
            field=models.JSONField(blank=True, default=list, help_text='List of art mediums/styles artist specializes in (painting, sculpture, etc.)'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short catchphrase or description under artist name', max_length=200),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='Total number of reviews received from customers'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time profile information was modified'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='user',
            field=models.OneToOneField(help_text='Links to the base User account for this artist', on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='artist',
            field=models.ForeignKey(help_text='The artist being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='artists.artistprofile'),
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='comment',
            field=models.TextField(help_text="Written review describing the customer's experience"),
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this review was submitted'),
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Star rating from 1 (poor) to 5 (excellent)'),
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='reviewer',
            field=models.ForeignKey(help_text='User who wrote this review (must be a customer)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ArtistAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_commissions', models.PositiveIntegerField(default=0)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('products_sold', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='artists.artistprofile')),
            ],
            options={
                'db_table': 'artist_analytics',
            },
        ),
        migrations.CreateModel(
            name='ArtistFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='artists.artistprofile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_artists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'artist_followings',
                'unique_together': {('follower', 'artist')},
            },
        ),
    ]
