# Generated by Django 5.2.4 on 2025-07-04 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcomment',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(help_text='Comment that was liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.forumcomment'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the like was created'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(help_text='User who liked the comment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this forum was created'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(help_text='Description of forum purpose and guidelines'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Whether forum is restricted to certain user groups'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(help_text="Display name of the forum (e.g., 'General Discussion', 'Technique Tips')", max_length=100),
        ),
        migrations.AlterField(
            model_name='forum',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of forum name', unique=True),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='author',
            field=models.ForeignKey(help_text='User who wrote this comment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='content',
            field=models.TextField(help_text='The actual comment text'),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When comment was posted'),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of users who have liked this comment'),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent comment if this is a reply (null for top-level comments)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.forumcomment'),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='post',
            field=models.ForeignKey(help_text='The forum post this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.forumpost'),
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time comment was edited'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(help_text='User who created this post', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=models.TextField(help_text='Main body text of the post'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When post was originally created'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='forum',
            field=models.ForeignKey(help_text='Forum this post belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.forum'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='URLs of images attached to this post'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Whether new comments are disabled on this post'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Whether post stays at top of forum (important announcements)'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of users who have liked this post'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='post_type',
            field=models.CharField(choices=[('discussion', 'Discussion'), ('job', 'Job Posting'), ('collaboration', 'Collaboration'), ('help', 'Help/Question'), ('showcase', 'Showcase')], default='discussion', help_text='Category of post for filtering and organization', max_length=20),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of post title', max_length=250),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Searchable keywords related to post content'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='title',
            field=models.CharField(help_text='Post headline/subject line', max_length=200),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time post content was edited'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='application_deadline',
            field=models.DateField(blank=True, help_text='Last date to apply for this position', null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.CharField(help_text='Name of hiring company or organization', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='contact_email',
            field=models.EmailField(help_text='Email address for job applications and inquiries', max_length=254),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When job was posted'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(help_text='Detailed job description, responsibilities, and role overview'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether job is still accepting applications'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('freelance', 'Freelance'), ('contract', 'Contract'), ('internship', 'Internship')], help_text='Type of employment being offered', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(help_text='Job location (city, remote, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='posted_by',
            field=models.ForeignKey(help_text='User/company who posted this job opportunity', on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='requirements',
            field=models.TextField(help_text='Required skills, experience, and qualifications'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='salary_range',
            field=models.CharField(blank=True, help_text="Compensation range (optional, e.g., '$50k-70k', 'Competitive')", max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of job title', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(help_text='Job title/position name', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time job details were modified'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the like was created'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(help_text='Post that was liked', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.forumpost'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(help_text='User who liked the post', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='commentlike',
            table=None,
        ),
        migrations.AlterModelTable(
            name='forum',
            table=None,
        ),
        migrations.AlterModelTable(
            name='forumcomment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='postlike',
            table=None,
        ),
    ]
