# Generated by Django 5.2.4 on 2025-07-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_forumcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='forum',
            table='forums',
        ),
    ]
