# Generated by Django 5.2.4 on 2025-07-04 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_forum_options_alter_forum_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When user joined this forum')),
                ('is_active', models.BooleanField(default=True, help_text='Whether membership is currently active')),
                ('notification_level', models.CharField(choices=[('all', 'All Posts'), ('mentions', 'Mentions Only'), ('none', 'No Notifications')], default='all', help_text='What level of notifications user receives from this forum', max_length=20)),
                ('forum', models.ForeignKey(help_text='The forum this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.forum')),
                ('user', models.ForeignKey(help_text='The user who is a member of this forum', on_delete=django.db.models.deletion.CASCADE, related_name='forum_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forum_memberships',
                'unique_together': {('forum', 'user')},
            },
        ),
    ]
