# Generated by Django 5.2.4 on 2025-07-04 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artistprofile_artist_statement_and_more'),
        ('chapters', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chaptermembership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='admin',
            field=models.ForeignKey(help_text='User responsible for managing this chapter', on_delete=django.db.models.deletion.CASCADE, related_name='managed_chapters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='city',
            field=models.CharField(help_text='Primary city this chapter serves', max_length=100),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Public email for chapter inquiries and communication', max_length=254),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Optional phone number for chapter contact', max_length=15),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='country',
            field=models.CharField(default='India', help_text='Country where chapter operates', max_length=100),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Header image representing the chapter and local art scene', null=True, upload_to='chapter_images/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this chapter was established on the platform'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(help_text="Detailed description of chapter's mission, activities, and community"),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether chapter is currently operational and accepting members'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(help_text="Display name of the chapter (e.g., 'Mumbai Chapter', 'Delhi Art Community')", max_length=100),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of chapter name for web addresses', unique=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text="Chapter's social media profiles and websites"),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='state',
            field=models.CharField(help_text='State or province where chapter is located', max_length=100),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time chapter information was modified'),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='chapter',
            field=models.ForeignKey(help_text='Chapter organizing this event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chapters.chapter'),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When event was first created'),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='created_by',
            field=models.ForeignKey(help_text='User who created/organized this event', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='description',
            field=models.TextField(help_text='Detailed event description, agenda, and requirements'),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='end_date',
            field=models.DateTimeField(help_text='Event end date and time'),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='event_type',
            field=models.CharField(choices=[('exhibition', 'Exhibition'), ('workshop', 'Workshop'), ('meetup', 'Meetup'), ('competition', 'Competition'), ('other', 'Other')], help_text='Category of event for filtering and organization', max_length=20),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='image',
            field=models.ImageField(blank=True, help_text='Event poster or promotional image', null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether event is open to all users or chapter members only'),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='location',
            field=models.CharField(help_text='Physical address or venue where event takes place', max_length=200),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of attendees (null for unlimited)', null=True),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost to attend event (0 for free events)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of event title', max_length=250),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='start_date',
            field=models.DateTimeField(help_text='Event start date and time'),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='title',
            field=models.CharField(help_text='Event name/title', max_length=200),
        ),
        migrations.AlterField(
            model_name='chapterevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time event details were modified'),
        ),
        migrations.AlterField(
            model_name='chaptermembership',
            name='artist',
            field=models.ForeignKey(help_text='The artist who is a member of this chapter', on_delete=django.db.models.deletion.CASCADE, related_name='chapter_memberships', to='artists.artistprofile'),
        ),
        migrations.AlterField(
            model_name='chaptermembership',
            name='chapter',
            field=models.ForeignKey(help_text='The chapter this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chapters.chapter'),
        ),
        migrations.AlterField(
            model_name='chaptermembership',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether membership is currently active (not suspended or left)'),
        ),
        migrations.AlterField(
            model_name='chaptermembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When artist joined this chapter'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='attended',
            field=models.BooleanField(default=False, help_text='Whether user actually attended the event (updated post-event)'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(help_text='The event this registration is for', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='chapters.chapterevent'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When user registered for the event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(help_text='User who registered for this event', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='chaptermembership',
            table=None,
        ),
        migrations.AlterModelTable(
            name='eventregistration',
            table=None,
        ),
    ]
